import { IcEye, IcX, IcCheck, IcTrophy, IcSparkle } from "./Icons";
import { USER, SKILLS_DATA, CHALLENGES_DATA } from "../portfolioData";
import SkillRow from "./SkillRow";
import CustomSections from "./CustomSections";

export default function EmployerPreview({ bio, headline, sections, onClose }) {
  const done = CHALLENGES_DATA.filter(c => c.status === "completed");
  const totalPts = done.reduce((a, c) => a + c.pts, 0);

  return (
    <div className="ep-overlay" onClick={e => e.target === e.currentTarget && onClose()}>
      <div className="ep-sheet">
        <div className="ep-topbar">
          <div className="ep-topbar-inner">
            <span className="ep-mode-pill">
              <IcEye /> Employer View
            </span>
            <span className="ep-mode-note">This is exactly what employers see when they visit your portfolio</span>
          </div>
          <button className="ep-close" onClick={onClose}>
            <IcX /> Close Preview
          </button>
        </div>

        <div className="ep-scroll">
          {/* Hero */}
          <div className="ep-hero">
            <div className="ep-hero-bg" />
            <div className="ep-hero-content">
              <div className="ep-av">{USER.initials}</div>
              <div className="ep-hero-info">
                <h1 className="ep-name">{USER.name}</h1>
                <p className="ep-headline">{headline}</p>
                <div className="ep-contact-row">
                  <span>📍 {USER.address}</span>
                  <span>✉️ {USER.email}</span>
                  <span>📞 {USER.phone}</span>
                </div>
                <div className="ep-tag-row">
                  <span className="ep-tag ep-tag-pwd">♿ {USER.disability}</span>
                  <span className="ep-tag ep-tag-field">{USER.field}</span>
                  <span className="ep-tag ep-tag-id">PWD {USER.pwdIdNo}</span>
                </div>
              </div>
            </div>
          </div>

          {/* Stats strip */}
          <div className="ep-stats-strip">
            {[
              { n: done.length, l: "Challenges Completed" },
              { n: totalPts.toLocaleString(), l: "Points Earned" },
              { n: `${SKILLS_DATA.length}`, l: "Skills Assessed" },
              { n: USER.memberSince.split(" ")[1], l: "Member Since" },
            ].map((s, i) => (
              <div key={i} className="ep-stat">
                <span className="ep-stat-n">{s.n}</span>
                <span className="ep-stat-l">{s.l}</span>
              </div>
            ))}
          </div>

          {/* Bio */}
          <div className="ep-section">
            <h3 className="ep-sec-title">About</h3>
            <p className="ep-bio">{bio}</p>
          </div>

          {/* Skills */}
          <div className="ep-section">
            <h3 className="ep-sec-title">Skill Proficiency</h3>
            <div className="ep-skills-grid">
              {SKILLS_DATA.map((s, i) => <SkillRow key={s.name} skill={s} i={i} />)}
            </div>
          </div>

          {/* Completed challenges */}
          <div className="ep-section">
            <h3 className="ep-sec-title">Completed Challenges ({done.length})</h3>
            <div className="ep-ch-table">
              {done.map(ch => (
                <div key={ch.id} className="ep-ch-row">
                  <div className="ep-ch-check"><IcCheck /></div>
                  <span className="ep-ch-title">{ch.title}</span>
                  <span className="ep-ch-tag">{ch.tag}</span>
                  <span className="ep-ch-date">{ch.date}</span>
                  <span className="ep-ch-pts"><IcTrophy />{ch.pts} pts</span>
                </div>
              ))}
            </div>
          </div>

          {/* Custom sections */}
          {sections.some(s => s.type === "links" || (s.type === "text" && s.content) || (s.type === "image" && s.src)) && (
            <div className="ep-section">
              <h3 className="ep-sec-title">Additional Information</h3>
              <CustomSections sections={sections} setSections={() => {}} readOnly={true} />
            </div>
          )}

          <div className="ep-footer">
            <IcSparkle /> Portfolio generated by InklusiJobs AI Platform · Last updated {USER.lastUpdated}
          </div>
        </div>
      </div>
    </div>
  );
}